# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa03c9c86f4ed54cc0ba86d44cebe3a737aac15d5693638224697a57e2fd16f1db2c1ff446f922830b0a566fbeeb77d260647b6040155231e95351a95d0657ef

test:
  secret_key_base: 588f4f0e8b7b79a4bdb4c10a13068af707aca5c23e92a978eafb858d728a079befd00431ff5462678490372ed024efe8af8a7de4e0c15e07c880e4f624bc78ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
